version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/rust
      - image: gcc:latest
    working_directory: ~/work
    steps:
      - checkout
      - run: ./libtest.sh

workflows:
  build:
    jobs:
      - build_and_test