version: 2.0

jobs:
  build_and_test:
    docker:
      - image: uta8a/circleci-rust-cmake:0.0.1
    environment:
      USER: uta8a
    working_directory: ~/work
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./libtest.sh

workflows:
  version: 2
  build:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master