version: 2.0

jobs:
  build_and_test:
    docker:
      - image: circleci/rust
      - image: rikorose/gcc-cmake:latest
    environment:
      USER: uta8a
    working_directory: ~/work
    steps:
      - checkout
      - run: ./libtest.sh

workflows:
  build:
    jobs:
      - build_and_test